---
# This role runs on Capsule servers to retrieve their certificate tarballs from the Satellite
# We should have already generated unique certificate tarballs on the Satellite for each Capsule(generate_capsule_tar)
# We use a fetch-then-copy pattern because it's the most reliable cross-platform method

- name: Distribute Capsule cert tarballs to Capsule hosts
  # The 'capsule_fqdns' list in group_vars is our master list of all Capsules
  # This condition checks: "Is this current host in the Capsule list?"
  # Only hosts in that list will run these tasks - all others skip
  when: inventory_hostname in capsule_fqdns
  block:
    - name: Process certificate distribution for this Capsule
      ansible.builtin.include_tasks: distribute_single_capsule_tar.yml